* Adaptive Governance Topics
** Managing common-pool resources
   * Water Rights
   * Game & Wildlife Population
     * Fisheries

** Intent-Matching 
   * Offer Networks:
     * AI market-making based on asserted (and potentially inferred) intents. This is similar to kidney networks where donor-types and recipients don't always match, except here there are chains of different offers and requests. Offernetworks.
     * balanced with perceived global health of the network by competing heterogeneous objective (functions), whose fitness is augmented by human input and interaction and other sensors/signals (the hypothesis here is that a singular objective function (make more $, increase production), without regard to external feedback leads to pathological structure)
** Adaptive Cities
** Automated Indoor Food Production
** Transportation
** Logistics & Distribution
** Crowd-Sourced Constitution?
   * [[http://www.taurillon.org/une-constitution-europeenne-pour-et-par-les-citoyens][Une Constitution européenne pour et par les citoyens - Le Taurillon, magazine eurocitoyenne]]   
** Adaptive Health-Care: Beyond Insurance