* Adaptive Governance Topics

** Example Contexts
*** Managing common-pool resources
    * Water Rights
    * Game & Wildlife Population
      * Fisheries
*** Attestations in a Decentralized context
    * Land Rights
*** Carbon Credit exchange market
*** Traffic/Parking Code
*** Intent-Matching 
    * Offer Networks:
      * AI market-making based on asserted (and potentially inferred) intents. This is similar to kidney networks where donor-types and recipients don't always match, except here there are chains of different offers and requests. Offernetworks.
      * balanced with perceived global health of the network by competing heterogeneous objective (functions), whose fitness is augmented by human input and interaction and other sensors/signals (the hypothesis here is that a singular objective function (make more $, increase production), without regard to external feedback leads to pathological structure)
*** Adaptive Cities
*** Automated Indoor Food Production
*** Transportation
*** Logistics & Distribution
*** Crowd-Sourced Constitution/Laws?
    * [[http://www.taurillon.org/une-constitution-europeenne-pour-et-par-les-citoyens][Une Constitution européenne pour et par les citoyens - Le Taurillon, magazine eurocitoyenne]]   
*** Adaptive Health-Care: Beyond Insurance and Social Security

* Approaches
  * Formal Logics (Rule-Based)
    * Knowledge Representation (KR)
    * Semantic Knowledge Graphs
    * advantage: starts with a formal language that a machine can process and which can be made understandable to a human (RDF, JSON-LD)
    * Linked Opend Data
      - [[http://lodlaundromat.org/][LOD Laundromat]]:
        Access to /all/ linked open data and data cleaning
      - [[https://json-ld.org/][JSON-LD - JSON for Linking Data]]
      - [[http://rdfa.info/]]
  * Statistical Models & Methods
    * Machine Learning Techniques
      * advantage: 
        - statistical methods are proving promising to scale
      * disadvantage:
        - needs a lot of data and processing power
        - not always clear how we got to final output
        - bias in data is reflected in output
        - results highly correlated/coupled with dataset learned on
        - cannot compose semantically with other system

* Design Goals
  * To demonstrate a general design pattern for a generic data-driven adaptive rules engine

** Dazza's Directives
  * following a /more general/ not more specific path for *simplest and shortest* route to a demo-able thing that is
    - sufficient relevant
    - ready to present
  * focus on a *technical governance automation* capability
    + Postulating some contexts:
       1. a voluntary carbon credit exchange market
       2. a municipal traffic/parking code) 
  * /data-centric/ (eg JSON other data file)
  * the data and code operate and complements the words spoken by the person demonstrating the code
  * *propose a project to code and describe*
    - the sort of data it would invest
    - the behavior it would exhibit
  * *solicit feedback from broader community* to help propose and specify relevant options
    - to suss out good alternatives to when selecting the specific “adaptation” functionality to be demonstrated. 
  * *savagely narrow in scope at the system rules level*
  * agnostic as to the rules governing specific software agents for the moment because they are different beasts and doing both risks ending up with nothing in time to demo
  * *system rules are the clearest type to demo adaptive governance in an economic system*
    + *rules that define and regulate*:
      - the types of market transactions
      - the combinations of parties/roles/relationships
      - the velocity/size/etc of deal flow
      - the range of goods/services exchanged

* Buildable Options
  - (eg: open source software, available API's and other services, other options, etc)